# reference:
#   * https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
#   * https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28#authentication-example-for-github-actions
#
# grant PR permission to GitHub Actions: `Allow GitHub Actions to create and approve pull requests`
#   * https://github.com/huaichaow/marked-toc-extension/settings/actions

name: Release
on: [ workflow_dispatch ]

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/huaichaow/marked-toc-extension/pulls \
            -f title='Amazing new feature' \
            -f body='Please pull these awesome changes in!' \
            -f head='release/main' \
            -f base='main'
