# reference: https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions

name: Release
run-name: ${{ github.actor }} is performing release on ${{ github.ref_name }} with ${{ github.sha }} 🚀
on: [ workflow_dispatch ]

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Ensure the branch is 'main'
        if: github.ref_name != 'main' && !startsWith(github.ref_name, 'customized')
        run: |
          echo "release can only run on branch main or customized/*"
          exit 1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
